- shell:
  - description: "[apps] Installing Rosetta"
    command: softwareupdate --install-rosetta --agree-to-license

- shell:
  - description: "[apps] Configuring brew"
    command: brew tap localsend/localsend

- brew:
    - httpie
    - localsend
    - wget

- cask:
    - caffeine
    - firefox
    - font-cascadia-code
    - iterm2
    - logi-options-plus
    - notion
    - orbstack
    - raycast
    - rectangle
    - scroll-reverser
    - spotify
    - the-unarchiver
    - visual-studio-code

- shell:
    - defaults write com.intelliscapesolutions.caffeine SuppressLaunchMessage -int 1
    - defaults write com.pilotmoon.scroll-reverser ReverseMouse -int 1
    - defaults write com.pilotmoon.scroll-reverser ReverseTrackpad -int 0
    - defaults write com.pilotmoon.scroll-reverser ReverseX -int 0
    - defaults write com.pilotmoon.scroll-reverser ReverseY -int 1
